# Generated by Django 4.2.1 on 2023-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapa',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
