# Generated by Django 4.2.1 on 2023-06-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0002_chapa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapa',
            name='img',
            field=models.URLField(default='https://conexaoplaneta.com.br/wp-content/uploads/2023/03/raposas-british-wildlife-photography-3-conexao-planeta.jpg'),
        ),
    ]
