# Generated by Django 4.2.1 on 2023-06-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0003_chapa_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapa',
            name='img',
            field=models.URLField(default='https://www.volvotrucks.cz/content/dam/volvo-trucks/markets/master/home/trucks/volvo-fh/others/volvo-fh-build-your-volvo-fh.jpg'),
        ),
    ]
