# Generated by Django 4.2.1 on 2023-06-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0004_alter_chapa_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapa',
            old_name='usuario',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='chapa',
            name='img',
            field=models.URLField(default='https://www.dataex.com.br/wp-content/uploads/2021/05/inteligencia-artificial-o-que-e-como-funciona-e-aplicacoes-praticas.jpg'),
        ),
    ]
