# Generated by Django 4.2.1 on 2023-06-09 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapa', '0005_rename_usuario_chapa_username_alter_chapa_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapa',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
