# Generated by Django 4.2.1 on 2023-06-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0006_alter_chapa_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapa',
            name='name_chapa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
