# Generated by Django 4.2.1 on 2023-06-13 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapa', '0007_chapa_name_chapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapa',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
